### ISSUE TITLE
List #1-16 example sentence for "obstacle, hitch" doesn't match

### ISSUE THREAD

**Issue by sorah** [mercari/engineer-vocabulary-list#3]
the example sentence for 1-16 "支障 = obstacle, hitch" uses "interfere" instead of "obstacle" nor "hitch".

> It interferes with it (our project).

**Comment by sorah** [comment]
Um, I've found more lines that example sentences don't align with words mentioned in the same line. If those are intentional, please disregard and close this issue.

**Comment by merasako** [comment]
Thank you for your comment! We tried to use the english word in the example sentences as long as possible, but some of them don't include them intentionally.
