### ISSUE TITLE
Why don't we have the primary source as a single text file (like csv or tsv) ?

### ISSUE THREAD

**Issue by DQNEO** [mercari/engineer-vocabulary-list#7]
First, thank you for this great innovation.
This work is valuable for the whole industry.

I have a suggestion.
Why don't we have the primary source as a text file (like csv or tsv) ?

* A text file can be easily converted into any forms (pdf, xlsx, html, etc). If we had it as a single text file,  we would not need to maintain duplicate resources 
* A text file would be more machine readable and machine friendly. It would be more natural for engineers and open source community. https://en.wikipedia.org/wiki/Unix_philosophy
* If we had it as a text file, contribution by a pull request would be much more easier.

**Comment by merasako** [comment]
Thank you for your suggestion! we uploaded csv files.
