### ISSUE TITLE
「チケットを取る」 is not an appropriate  usage in Japanese

### ISSUE THREAD

**Issue by DQNEO** [mercari/engineer-vocabulary-list#8]
IMO, 「チケットを取る」means to purchase or reserve a ticket for a concert or a flight.

If we mean "take an issue" in an issue tracking system, a normal Japanese verb would be 
「チケットを引き受ける」or 「チケットを着手する」

**Comment by merasako** [comment]
Thanks for this feedback! Of course you are right, but the meaning can change depending on the context.

**Comment by DQNEO** [comment]
OK I searched internal Slack and found some usage of 「チケットを取る」 for  "Take on a task".
So my suggestion is not good.

Thanks for the feedback!
