### ISSUE TITLE
Add "ログインできました"

### ISSUE THREAD

**Issue by DQNEO** [mercari/engineer-vocabulary-list#9]
IMO, one of the most common mistakes for Japanese speakers is the usage of "could".

I have seen many Japanese people say:

* I could login (for ログインできました)
* I could buy the item (for 商品を購入できました)

But actually these usage of "could" sound like subjunctive, right ? 

So I would suggest we add this case to the list.

* I was able to login / I successfully logged in (for ログインできました)

**Comment by merasako** [comment]
These are some good suggestions, thanks! We will consider adding them if we have the chance to create a new list.
